interface sava_ModelResponse {

    domain: null,
    _events: {
        finish: [any],
        end: [any]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    output: [any],
    outputEncodings: [any],
    outputCallbacks: [any],
    outputSize: 0,
    writable: true,
    _last: false,
    upgrading: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: true,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: false,
    _headerSent: false,
    socket: {
        connecting: false,
        _hadError: false,
        _handle: {
            bytesRead: 1176,
            _externalStream: [External],
            fd: -1,
            reading: true,
            owner: [any],
            onread: [any],
            onconnection: null,
            writeQueueSize: 0,
            _consumed: true
        },
        _parent: null,
        _host: null,
        _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [Object],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
        },
        readable: true,
        domain: null,
        _events: {
            end: [any],
            finish: [any],
            _socketEnd: [any],
            drain: [any],
            timeout: [any],
            data: [any],
            error: [any],
            close: [any],
            resume: [any],
            pause: [any]
        },
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [any],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [any]
        },
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 419,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: {
            domain: null,
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [Object],
            _usingSlaves: false,
            _slaves: [any],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::80'
        },
        _server: {
            domain: null,
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [Object],
            _usingSlaves: false,
            _slaves: [any],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::80',
        },
        _idleTimeout: 120000,
        _idleNext: {
            _idleNext: [any],
            _idlePrev: [any],
            _timer: [Object],
            _unrefed: true,
            msecs: 120000,
            nextTick: false
        },
        _idlePrev: {
            _idleNext: [any],
            _idlePrev: [any],
            _timer: [Object],
            _unrefed: true,
            msecs: 120000,
            nextTick: false
        },
        _idleStart: 16496,
        _destroyed: false,
        parser: {
            _headers: [any],
            _url: '',
            _consumed: true,
            socket: [any],
            incoming: [Object],
            outgoing: null,
            maxHeaderPairs: 2000,
            onIncoming: [any]
        },
        on: [any],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: [any],
        _peername: {
            address: '::1',
            family: 'IPv6',
            port: 64121
        }
    },
    connection: {
        connecting: false,
        _hadError: false,
        _handle: {
            bytesRead: 1176,
            _externalStream: [External],
            fd: -1,
            reading: true,
            owner: [any],
            onread: [any],
            onconnection: null,
            writeQueueSize: 0,
            _consumed: true
        },
        _parent: null,
        _host: null,
        _readableState: {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [Object],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
        },
        readable: true,
        domain: null,
        _events: {
            end: [any],
            finish: [any],
            _socketEnd: [any],
            drain: [any],
            timeout: [any],
            data: [any],
            error: [any],
            close: [any],
            resume: [any],
            pause: [any]
        },
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [any],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object]
        },
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 419,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: {
            domain: null,
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [Object],
            _usingSlaves: false,
            _slaves: [any],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::80'
        },
        _server: {
            domain: null,
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [Object],
            _usingSlaves: false,
            _slaves: [any],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::80'
        },
        _idleTimeout: 120000,
        _idleNext: {
            _idleNext: [any],
            _idlePrev: [any],
            _timer: [Object],
            _unrefed: true,
            msecs: 120000,
            nextTick: false
        },
        _idlePrev: {
            _idleNext: [any],
            _idlePrev: [any],
            _timer: [Object],
            _unrefed: true,
            msecs: 120000,
            nextTick: false
        },
        _idleStart: 16496,
        _destroyed: false,
        parser: {
            _headers: [any],
            _url: '',
            _consumed: true,
            socket: [any],
            incoming: [Object],
            outgoing: null,
            maxHeaderPairs: 2000,
            onIncoming: [any]
        },
        on: [any],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: [any],
        _peername: {
            address: '::1',
            family: 'IPv6',
            port: 64121
        }
    },
    _header: null,
    _onPendingData: [any],
    _sent100: false,
    _expect_continue: false,
    req: {
        readable: false,
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        socket: {
            connecting: false,
            _hadError: false,
            _handle: [Object],
            _parent: null,
            _host: null,
            _readableState: [Object],
            readable: true,
            domain: null,
            _events: [Object],
            _eventsCount: 10,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: true,
            allowHalfOpen: true,
            _bytesDispatched: 419,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: [Object],
            _server: [Object],
            _idleTimeout: 120000,
            _idleNext: [Object],
            _idlePrev: [Object],
            _idleStart: 16496,
            _destroyed: false,
            parser: [Object],
            on: [any],
            _paused: false,
            read: [Function],
            _consuming: true,
            _httpMessage: [any],
            _peername: [Object]
        },
        connection: {
            connecting: false,
            _hadError: false,
            _handle: [Object],
            _parent: null,
            _host: null,
            _readableState: [Object],
            readable: true,
            domain: null,
            _events: [Object],
            _eventsCount: 10,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: true,
            allowHalfOpen: true,
            _bytesDispatched: 419,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: [Object],
            _server: [Object],
            _idleTimeout: 120000,
            _idleNext: [Object],
            _idlePrev: [Object],
            _idleStart: 16496,
            _destroyed: false,
            parser: [Object],
            on: [any],
            _paused: false,
            read: [Function],
            _consuming: true,
            _httpMessage: [any],
            _peername: [Object]
        },
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: {
            host: 'localhost',
            connection: 'keep-alive',
            'content-length': '243',
            accept: 'application/json, text/plain, */*',
            origin: 'http://localhost:51527',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
            'content-type': 'application/json;charset=UTF-8',
            referer: 'http://localhost:51527/web/main.html',
            'accept-encoding': 'gzip, deflate, br',
            'accept-language': 'en-US,en;q=0.8'
        },
        rawHeaders: ['Host',
            'localhost',
            'Connection',
            'keep-alive',
            'Content-Length',
            '243',
            'Accept',
            'application/json, text/plain, */*',
            'Origin',
            'http://localhost:51527',
            'User-Agent',
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
            'Content-Type',
            'application/json;charset=UTF-8',
            'Referer',
            'http://localhost:51527/web/main.html',
            'Accept-Encoding',
            'gzip, deflate, br',
            'Accept-Language',
            'en-US,en;q=0.8'],
        trailers: {},
        rawTrailers: [any],
        upgrade: false,
        url: '/api/gst/stock_transaction',
        method: 'POST',
        statusCode: null,
        statusMessage: null,
        client: {
            connecting: false,
            _hadError: false,
            _handle: [Object],
            _parent: null,
            _host: null,
            _readableState: [Object],
            readable: true,
            domain: null,
            _events: [Object],
            _eventsCount: 10,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: true,
            allowHalfOpen: true,
            _bytesDispatched: 419,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: [Object],
            _server: [Object],
            _idleTimeout: 120000,
            _idleNext: [Object],
            _idlePrev: [Object],
            _idleStart: 16496,
            _destroyed: false,
            parser: [Object],
            on: [any],
            _paused: false,
            read: [Function],
            _consuming: true,
            _httpMessage: [any],
            _peername: [Object]
        },
        _consuming: true,
        _dumped: false,
        next: [any],
        baseUrl: '',
        originalUrl: '/api/gst/stock_transaction',
        _parsedUrl: {
            protocol: null,
            slashes: null,
            auth: null,
            host: null,
            port: null,
            hostname: null,
            hash: null,
            search: null,
            query: null,
            pathname: '/api/gst/stock_transaction',
            path: '/api/gst/stock_transaction',
            href: '/api/gst/stock_transaction',
            _raw: '/api/gst/stock_transaction'
        },
        params: {},
        query: {},
        res: [any],
        _startAt: [150394, 349896483],
        _startTime: 2017
        body: {
            // warehouse_id: '59854d78cbb2601d68755cbc',
            // transaction_type: 'Manufacturing',
            // inventory_id: '597d695581408610241b86b3',
            // transaction_date: '2017-08-07T18:30:00.000Z',
            // debit_qty: 0,
            // credit_qty: 100,
            // owner: '5971ec82d805c61c70837cbc',
            // active: 1
        },
        _body: true,
        length: undefined,
        read: [Function],
        route: {
            path: '/api/gst/stock_transaction',
            stack: [any],
            methods: [Object]
        },
        quer: {
            _mongooseOptions: {},
            mongooseCollection: [Object],
            model: [Object],
            schema: [Object],
            op: 'find',
            options: [Object],
            _conditions: [Object],
            _fields: undefined,
            _update: undefined,
            _path: 'active',
            _distinct: undefined,
            _collection: [Object],
            _traceFunction: undefined,
            _castError: null,
            _count: [Function],
            _execUpdate: [Function],
            _find: [Function],
            _findOne: [Function],
            _findOneAndRemove: [Function],
            _findOneAndUpdate: [Function],
            _replaceOne: [Function],
            _updateMany: [Function],
            _updateOne: [Function]
        },
        templatePath: 'created'
    },
    locals: {
        bundle: any,
        status_code: 200 | 201 | 204
    },
    _startAt: any,
    _startTime: any,
    writeHead: [any]
}
